Python 3.5 POCL:
  script:
  - export PY_EXE=python3.5
  - export PYOPENCL_TEST=portable
  - export EXTRA_INSTALL="numpy mako pybind11 pyopencl"
  - export NO_SUBMODULES=1
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3.5
  - pocl
  except:
  - tags

# Python 3.5 with CUDA:
#   script:
#   - export PY_EXE=python3.5
#   - export PYOPENCL_TEST=portable
#   - export EXTRA_INSTALL="numpy"
#   - export NO_SUBMODULES=1
#   - export REQUIREMENTS_TXT=requirements-cuda.txt
#   - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
#   - ". ./build-and-test-py-project.sh"
#   tags:
#   - python3.5
#   - pocl
#   - nvidia-titan-x
#   except:
#   - tags

Documentation:
  script:
  - EXTRA_INSTALL="numpy mako pybind11 pyopencl"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-docs.sh
  - ". ./build-docs.sh"
  tags:
  - python3.5
  only:
  - master

Flake8:
  script:
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-flake8.sh
  - ". ./prepare-and-run-flake8.sh numloopy test"
  tags:
  - python3.5
  except:
  - tags
